### ISSUE TITLE
Fail to load native library libAstral.so

### ISSUE THREAD

**Issue by Lamm-a** [chaoszhang/A-pro#6]
I am getting `java.lang.NullPointerException` as a result of `libAstral.so` not being loaded.

I have downloaded an unziped the git onto my lunix machine and run `make.sh` and am then running the default test command with an added `-Xmx` due to need more space for object heap.

`java -Xmx512m -D"java.library.path=/lib/" -jar astral.1.1.2.jar -i test_data/song_primates.424.gene.tre`

This is resulting in:

```
Error:
 Fail to load native library libAstral.so.
 Make sure you are using the correct Djava.library.path (to the `lib` directory under ASTRAL-Pro where libAstral.so can be found).
 Trying running make.sh. For mode debugging, run: java -Djava.library.path=lib/ -jar native_library_tester.jar
```
I have tried the suggest debugging and get no feedback, I assume showing no bugs. The `libAstral.so` file is indeed located in the correct `Djava.library.path` as I have not change any directory structure and am working within `ASTRAL-MP`

```
find . -name "libAstral.so"
./lib/libAstral.so
```

Any ideas?

**Comment by chaoszhang** [comment]
Hi Lamm-a,
Thanks for trying our new program. My first intuition is that D"java.library.path=/lib/" should have been D"java.library.path=lib/" 
If fixing such does not solve the problem, please let me know.
Best regards,
Chao Zhang

**Comment by Lamm-a** [comment]
Hi Chao, unfortunately that does not fix the problem.

**Comment by chaoszhang** [comment]
Hi Lamm-a,
I need more information to diagnose this problem. Can you first `cd ASTRAL-MP` and run `bash make.sh`. Then run `java -Xmx512m -D"java.library.path=lib/" -jar astral.1.1.2.jar -i ../example/example1.tre` and paste the debug information of both commands here?
Best,
Chao

**Comment by openpaul** [comment]
I have the same issue, I am using commit 5818744

Hope this is not my mistake:

I did:
```
git clone https://github.com/chaoszhang/A-pro
cd A-pro/ASTRAL-MP
bash make.sh
```

Compilation seems to have worked, as I get the 1.1.3 version jar file. 

```
Build finished successfully. You can distribute Astral.1.1.3.zip or simply run astral.1.1.3.jar. 
  Note that if you are moving astral.1.1.3.jar to some other location, you need to also move the lib directory.
```

So then I launch it:

```
java -Xmx512m -D"java.library.path=lib/" -jar astral.1.1.3.jar -i ../example/example1.tre
```
With the output:

```

================== ASTRAL-Pro ===================== 

This is ASTRAL-Pro (A-Pro) version 1.1.3

Error: 
 Fail to load native library libAstral.so. 
 Make sure you are using the correct Djava.library.path (to the `lib` directory under ASTRAL-Pro where libAstral.so can be found). 
 Trying running make.sh. For mode debugging, run: java -Djava.library.path=lib/ -jar native_library_tester.jar

Exception in thread "main" java.lang.NullPointerException
        at phylonet.coalescent.CommandLine.exitWithErr(CommandLine.java:54)
        at phylonet.coalescent.CommandLine.main(CommandLine.java:486)
```
I also tried version 1.1.2 at commit 86c99db but got the same error. 

Hope this helps. I can also open a new issue, but it seemed to relate to this one quite a bit.

**Comment by chaoszhang** [comment]
My guess is that this pipeline failed to find the correct jni.h file (aka, finding a different version of JAVA).
If you are confident with compiling C++, you can try to find the correct path to jni.h and run `g++ -std=c++11 -I"$PATH_TO_JNI" -I"$PATH_TO_JNI" -march=native -Ofast -fPIC -o lib/libAstral.so -shared main/phylonet_coalescent_Polytree_PTNative.cpp`.
Alternatively, you can try C++ version of A-PRO at https://github.com/chaoszhang/ASTER and you just need to compile using `g++ -std=gnu++11 -march=native -Ofast -pthread astral-pro.cpp -o astral-pro` and run using `./astral-pro ../example/example1.tre`.
