### ISSUE TITLE
-a flag seeming to not work

### ISSUE THREAD

**Issue by Lamm-a** [chaoszhang/A-pro#7]
I have around 122 (so 122 orthologs) from 34 different genomes and I am trying to use the `-a` flag to collapse the gene trees into a phylogenetic tree with 34 nodes but it is not working. I just get a tree with the `number of nodes == number of gene trees`

I believe I am formatting the input file for -a correctly:
```
#Format
species_name: gene1,gene2,gene3,gene4,gene5
#Example
RB17:bacteria_RB17_1874945at2,bacteria_RB17_1830156at2,bacteria_RB17_1940575at2,bacteria_RB17_932854at2,bacteria_RB17_1701531at2,bacteria_RB17_1842956at2,bacteria_RB17_1676462at2
```

Where `RB17` is the species name  and the gene name in a node name for the gene tree `1874945at2` being  ` bacteria_RB17_1874945at2`. 

So I have a gene tree for `1874945at2` with 34 nodes where each node if formatted as `bacteria_[sample_name]_[gene_name]` and so on like this for.

Is a potential reason because Astral PRO is reading in 2136 trees from my multi tree nwk file? it does however say the correct number of input trees?

```
The number of input tree read is 122
2138 trees read from /home/lamma/faststorage/actinobacteria/busco/busco_nt/raxml-ng-output/gene_trees.nwk
122 extra trees.
All output trees will be *arbitrarily* rooted at bacteria_RB1_1009041at2
```

I am happy to share the whole gene list file and gene trees.nwk file if you would like :)

**Comment by chaoszhang** [comment]
Hi Lamm-a,
Sorry for the confusion, can you use the following format instead?
`bacteria_RB17_1874945at2 RB17
bacteria_RB17_1830156at2 RB17
bacteria_RB17_1940575at2 RB17`
Best regrads,
Chao Zhang

**Comment by Lamm-a** [comment]
Hi Chao,

so for each gene a new line of 

`gene_name species_name`

I will try this,
thanks :)

**Comment by smirarab** [comment]
Chao, would be good to update to support both formats.
